version: "3.0"

services:
  traffic_mapper:
    container_name: traffic_mapper_shiny
    # To build the image locally, comment out "image" below, and uncomment
    # "build" and the lines indented under it.
    # image: artificiallyintelligent/shiny_lite
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SRC_TAG: "traffic_mapper"
        SRC_IMAGE: "artificiallyintelligent/shiny_lite"
        DISCOVERY: "TRUE"
        PROJECT_PACKAGES: "config,shiny,shinycssloaders,shinyjs,shinyWidgets,stringr,scales,waiter,dplyr,data.table,geojson,mongolite,ggplot2,ggiraph,ggiraphExtra,RColorBrewer,viridis,hrbrthemes,lattice,leaflet,units"
        PROJECT_PACKAGES_PLUS: 
        DEPENDENCY: 
    restart: always
    # Setting this to something other than 'root' will cause shiny apps not to
    # run on the localhost:80 "Welcome to Shiny" diagnostics page mentioned
    # below.
    user: 'root'
    # Uncomment the lines below to disable application logs STDOUT output
    environment:
      - R_CONFIG_FILE=/usr/local/lib/shiny-server/config_mount/config.yaml
      - DISCOVER_PACKAGES=FALSE
      - DEPENDENCY_INSTALL=FALSE
      - INSTALL_PACKAGE_AT_RUNTIME=FALSE
      - SHINY_APP_IDLE_TIMEOUT=5
      - SHINY_APP_INIT_TIMEOUT=60
      - SHINY_GOOGLE_ANALYTICS_ID=
      - PORT=8080
      - APPLICATION_LOGS_TO_STDOUT=TRUE
    ports:
      - '8080:8080'
    volumes:
      - shiny_logs:/var/log/shiny-server
      # Comment the lines below out for initial testing. With it commented out,
      # going to localhost:80 in one's web browser will show a "Welcome to
      # Shiny Server!" diagnostics page.
      # - './mountpoints/apps:/srv/shiny-server'
      # - ./mountpoints/apps:/etc/cont-init.d
      - 'C:/Users/Stuart/GitHub/traffic_mapper/Rscripts/conf:/usr/local/lib/shiny-server/config_mount'
volumes:
  shiny_logs:
