default:
  datawarehouse:
    driver: 'MySQLDriver' 
    server: 'unraiden.local'
    uid: 'stuart'
    pwd: 'WZ8yb9&&rBPw'  
    port: 3306
    database: 'traffic_mapper'
  azure_primary:
    url: "https://shiny.documents.azure.com:443/;AccountKey=H26KAgdzCIkVsK5Njh8SlFCDV8O41SD0YbHY6dZnvUv6Ec70FNyKxMb8cvzso1FFSA0FYdZ6gkKCgw96onyEjA==;"
    mongo_url: "mongodb://shiny:H26KAgdzCIkVsK5Njh8SlFCDV8O41SD0YbHY6dZnvUv6Ec70FNyKxMb8cvzso1FFSA0FYdZ6gkKCgw96onyEjA==@shiny.documents.azure.com:10255/mean-dev?ssl=true"

azure:
  datawarehouse:
    driver: 'MySQLDriver' 
    server: 'unraiden.local'
    uid: 'stuart'
    pwd: 'WZ8yb9&&rBPw'  
    port: 3306
    database: 'traffic_mapper'
  azure_primary:
    url: "https://shiny.documents.azure.com:443/;AccountKey=H26KAgdzCIkVsK5Njh8SlFCDV8O41SD0YbHY6dZnvUv6Ec70FNyKxMb8cvzso1FFSA0FYdZ6gkKCgw96onyEjA==;"
    mongo_url: "mongodb://shiny:H26KAgdzCIkVsK5Njh8SlFCDV8O41SD0YbHY6dZnvUv6Ec70FNyKxMb8cvzso1FFSA0FYdZ6gkKCgw96onyEjA==@shiny.documents.azure.com:10255/mean-dev?ssl=true"
